### PR TITLE
Huggingface Spaces Web Demo

### PR DESCRIPTION
**Pull request by AK391**
Web Demo on Huggingface Spaces using Gradio

### CODE REVIEW

**Comment by bowenc0221** [comment]
Did you accidentally put the Swin Transformer link in README?

**Comment by AK391** [comment]
@bowenc0221 yes sorry will update the correct link soon https://huggingface.co/spaces/akhaliq/Mask2Former

**Comment by AK391** [comment]
@bowenc0221 thanks, updated the link

**Comment by bowenc0221** [comment]
Thanks for the demo.

**Comment by niemiaszek** [comment]
@AK391 Hello, demo seems to be broken - there is some error with pip installation of fvcore. Could you have a look, Please? I would love to try out this demo

**Comment by AK391** [comment]
@niemiaszek Hi thanks for letting me know the demo should be back up now

**Comment by tracyhenry** [comment]
May you share what model is used in the demo?

**Pull request merged**
